### ISSUE TITLE
Frontend TODO

### ISSUE THREAD

**Issue by JoeNibe** [p0lygun/astounding-arapaimas#30]
- [ ] Color schema (poopie working on it)

- [ ] Game screen requires additional components (conquered pieces, current move etc)

- [ ] Display settings with input for token

- [ ]  Fix the enter key to highlight the latest chess piece selection

- [ ]  Checkmate, Stalemate, Check detection
